version: 2
commands:
  build-and-run:
    steps:
      - (省略)
      - run:
          name: install Java
          command: |
            sudo apt update
            sudo apt install default-jre
      - allure/install
      - run:
          name: run tests
          command: |
            bundle exec rspec \
            --format progress \
            --format AllureRspecFormatter
          environment:
            HEADLESS_MODE: true
            LANG: ja_JP.UTF-8
      - store_test_results:
          path: reports
      - store_artifacts:
          path: tmp/screenshots
      - run:
          name: clean Allure report generation path
          command: rm -rf reports/allure-report
      - run:
          name: Allure report generation
          command: |
            allure generate \
            --report-dir reports/allure-report \
            --clean \
            reports/allure-results
          when: always
      - store_artifacts:
          path: reports/allure-report
          destination: Report/Allure
          when: always